development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dont_be_a_tourist
  pool: 5
  username: root
  password: tmedia
  host: 192.168.0.41

production:
  adapter: mysql2
  database: dbat2_dbat2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  port: 3306
  username: dbat2
  password: sightsee47#!

